resposta = []
gabarito = ["b","c","d","c","c","d","e","a","a","c", ]

print("Bem vindo ao Quiz sobre Desmatamento")
print()
print("Regras do Quiz :")
print()
print("O jogo será feito em forma de quiz com 10 questões de múltipla escolha (a ate e)")
print()
print("Lembrando de sempre digitar a resposta das letras em letra minuscula")
print()
print("Sem consultar a internet ou qualquer aparelho eletronico que possa te auxiliar no quiz a fim de ajudar no seu aprendizado")
print()
def entrada():
    for i in range(1):
        print()
        print("Oque é desmatamento ?")
        print("a)consiste no reflorestamento de cobertura vegetal")
        print("b)consiste na retirada da cobertura vegetal parcial ou total de um determinado lugar")
        print("c)é uma pratica totalmente legal que consiste na retirada de cobertura vegetal de um determinado lugar")
        print("d)é a criação de novas arvores e novas formas de ecossistema sustentavel")
        print()
        resp = input("Resposta:")
        resposta.append(resp)
        print()
        print("Quais são as consequências do desmatamento?")
        print("a)As consequencias do desmatamento são basicamente relacionadas a falta de oxigenio")
        print("b)O desmatamento apresenta consequencias pouco importantes para o meio ambiente , porem em relação a area urbana apresenta diversas consequencias")
        print("c)As principais consequências do desmatamento são a perda de biodiversidade, aquecimento global , e contribuição para o efeito estufa")
        print("d)O desmatamento não apresenta consequencias relevantes")
        print()
        resp = input("Resposta:")
        resposta.append(resp) 
        print("O desmatamento pode trazer diversas consequências para a sociedade e ambiente, EXCETO:")
        print("a) Aumento do processo de erosão dos solos.")
        print("b) Modificações climáticas com elevação da temperatura.")
        print("c) Provocar a desertificação em extensas áreas.")
        print("d) Diminuição do processo de erosão dos solos.")
        print()
        resp = input("Resposta:")
        resposta.append(resp)
        print()
        print("O desmatamento é hoje um dos principais problemas relacionados ao meio ambiente. Assinale a alternativa incorreta:")
        print("a) Desmatamento consiste no processo de retirada da cobertura vegetal de uma determinada área.")
        print("b)A retirada da cobertura vegetal interfere no equilíbrio natural do ambiente, podendo gerar problemas como empobrecimento do solo, perda de habitat de animais, alteração dos cursos d'água, entre outros.")
        print("c) O desmatamento afeta a qualidade dos solos positivamente, visto que a retirada da cobertura vegetal permite a lavagem do solo pela água da chuva com maior facilidade")
        print("d) Um dos maiores efeitos do desmatamento está relacionado com o aumento do aquecimento global. A retirada da vegetação reduz a umidade do ar das áreas, diminuindo os índices pluviométricos e aumentando as temperaturas consideravelmente.")
        print()
        resp = input("Resposta:")
        resposta.append(resp)
        print()
        print("O desmatamento é, sem dúvidas, uma das maiores preocupações atuais da humanidade, pois o seu avanço poderá intensificar o processo de remoção da cobertura vegetal do planeta. Podemos identificar como consequências do desmatamento todas as alternativas a seguir, exceto:")
        print("a) o aumento do efeito estufa")
        print("b) a diminuição da biodiversidade")
        print("c) a elevação desproporcional da umidade")
        print("d) o maior desgaste do solo")
        print("e) o assoreamento de rios e lagos")
        print()
        resp = input("Resposta:")
        resposta.append(resp)
        print()
        print("A questão ambiental, uma das principais pautas contemporâneas, possibilitou o surgimento de concepções políticas diversas, dentre as quais se destaca a preservação ambiental, que sugere uma ideia de intocabilidade da natureza e impede o seu aproveitamento econômico sob qualquer justificativa.")
        print("Considerando as atuais concepções políticas sobre a questão ambiental, a dinâmica caracterizada no texto quanto à proteção do meio ambiente está baseada na:")
        print("a) prática econômica sustentável")
        print("b) contenção de impactos ambientais")
        print("c) utilização progressiva dos recursos naturais")
        print("d) proibição permanente da exploração da natureza")
        print("e) definição de áreas prioritárias para a exploração econômica")
        print()
        resp = input("Resposta:")
        resposta.append(resp)
        print()
        print("Se considerarmos que existe uma relação direta entre a crise ambiental que o planeta enfrenta atualmente e a lógica da acumulação capitalista, qual das afirmações abaixo NÃO JUSTIFICA esta afirmação?")
        print("a)as estruturas de poder que controlam o uso dos recursos naturais e do meio ambiente comum estão baseadas no cálculo econômico privado das empresas, e este cálculo não considera as condições globais do meio ambiente, mas apenas os elementos mercantis")
        print("b) vivemos o risco de ruptura do equilíbrio ecológico do planeta pela incapacidade de os agentes econômicos se ajustarem às capacidades limitadas de suporte do meio ambiente")
        print("c) existem dois fatores de extrema importância que atuam simultaneamente no sentido do agravamento da crise ambiental: a concentração crescente do controle sobre os recursos naturais e a privatização do uso do meio ambiente comum")
        print("d) a solução da crise ambiental passa pela democratização do controle sobre os recursos naturais e pela desprivatização do meio ambiente comum, de tal forma que o acesso aos recursos naturais expressa uma vivência democrática efetiva")
        print("e) as proposições relativas à determinação de um elemento da sociedade por outro, como, por exemplo, a crise ambiental decorrente da forma como se dá a exploração econômica, não devem ser seriamente consideradas, pois há uma infinidade de outras causas não econômicas para a crise ambiental")
        print()
        resp = input("Resposta:")
        resposta.append(resp)
        print()
        print("A linhagem dos primeiros críticos ambientais brasileiros não praticou o elogio laudatório da beleza e da grandeza do meio natural brasileiro. O meio natural foi elogiado por sua riqueza e potencial econômico, sendo sua destruição interpretada como um signo de atraso, ignorância e falta de cuidado.")
        print("Descrevendo a posição dos críticos ambientais brasileiros dos séculos XVIII e XIX, o autor demonstra que, via de regra, eles viam o meio natural como:")
        print("a) ferramenta essencial para o avanço da nação")
        print("b) dádiva divina para o desenvolvimento industrial")
        print("c) paisagem privilegiada para a valorização fundiária")
        print("d) limitação topográfica para a promoção da urbanização")
        print("e) obstáculo climático para o estabelecimento da civilização")
        resp = input("Resposta:")
        resposta.append(resp)
        print()
        print("O crescimento precipitado das cidades em decorrência do acelerado desenvolvimento tecnológico da segunda metade do século XX produziu um espaço urbano cada vez mais fragmentado, caracterizado pelas desigualdades e segregação espacial, subemprego e submoradia, violência urbana e graves problemas ambientais.")
        print("Sobre os problemas socioambientais nos espaços urbano-industriais, é correto afirmar que:")
        print("a) os resíduos domésticos e industriais aliados aos numerosos espaços marginalizados, problemas de transportes, poluição da água e do solo, bem como os conflitos sociais, são grandes desafios das cidades na atualidade.")
        print("b) as ações antrópicas, em particular, as atividades ligadas ao desenvolvimento industrial e urbano, têm comprometido a qualidade das águas superficiais, sem, contudo, alcançar os depósitos subterrâneos.")
        print("c) os conflitos sociais existentes no espaço urbano mundial estão associados à ampliação de políticas públicas para melhoria de infraestrutura que provocou o deslocamento de milhões de pessoas do campo para a cidade.")
        print("d) a violência urbana, problema agravado nos últimos anos, está associada à má distribuição de renda, à livre comercialização de armas de fogo e à cultura armamentista existente na maioria dos países europeus.")
        print("e) a chuva ácida ocorrida nos países ricos industrializados apresenta como consequências a destruição da cobertura vegetal e a alteração das águas, embora favoreça a fertilização dos solos agricultáveis.")
        print()
        resp = input("Resposta:")
        resposta.append(resp)
        print()
        print("Em Salvador e na região metropolitana, são descartados, por ano, cerca de dois milhões de toneladas de resíduos sólidos. Se não forem tomadas providências, em pouco tempo, os aterros sanitários não serão suficientes para manter tanto lixo.")
        print("Considerando-se a problemática do lixo das grandes regiões metropolitanas do país, entre as soluções corretas para reduzir o acúmulo desse material nos aterros sanitários, pode-se incluir")
        print("a) a incineração de resíduos sólidos descartados nos aterros sanitários.")
        print("b) o incentivo às cooperativas de catadores e aos artesões para transformar os resíduos sólidos em material reciclado.")
        print("c) o reaproveitamento de resíduos com objetivo de requalificá-los e introduzi-los na economia.")
        print("d) a ampliação de aterros sanitários para aproveitar a energia gerada na biodecomposição de resíduos sólidos.")
        print("e) a modernização da frota de caminhões, que utilize óleo diesel isento de enxofre, para manter os grandes centros urbanos limpos.")
        print()
        resp = input("Resposta:")
        resposta.append(resp)      
        
def correcao():
    ct = 0
    for i in range(10):
        if resposta[i] == gabarito[i]:
            ct = ct + 1
    if (ct >= 0 and ct <= 5):
        print("Infelizmente você precisa estudar mais sobre o assunto")
        print()
        print(" Segue abaixo alguns sites que irão te ajudar a desenvolver mais sobre o assunto:")
        print()
        print("https://brasilescola.uol.com.br/geografia/o-desmatamento.htm#:~:text=Desmatamento%2C%20tamb%C3%A9m%20chamado%20de%20desflorestamento%2C%20consiste%20na%20retirada,como%20um%20dos%20maiores%20problemas%20ambientais%20da%20atualidade.")
        print()
        print("https://www.todamateria.com.br/desmatamento/")
        print()
        print(" Os sites do brasilescola e todamateria são sites extremamente educativos que iram te ajudar a estudar sobre desmatamente e muitos outros temas")
    elif (ct > 5 and ct <=7):
        print("Você foi muito bem , porem ainda tem alguns assuntos que você deveria estudar mais")
        print()
        print(" Segue abaixo alguns sites que irão te ajudar a desenvolver mais sobre o assunto:")
        print()
        print("https://brasilescola.uol.com.br/geografia/o-desmatamento.htm#:~:text=Desmatamento%2C%20tamb%C3%A9m%20chamado%20de%20desflorestamento%2C%20consiste%20na%20retirada,como%20um%20dos%20maiores%20problemas%20ambientais%20da%20atualidade.")
        print()
        print("https://www.todamateria.com.br/desmatamento/")
        print()
        print(" Os sites do brasilescola e todamateria são sites extremamente educativos que iram te ajudar a estudar sobre desmatamente e muitos outros temas")
    elif (ct > 7 and ct <=10):
        print("Parabens você é uma pessoa extremamente atualizada sobre esse assunto tão importante, continue assim dedicado em estudar e desenvolver sobre assuntos atuais e extremamente importantes")
    return ct
    
def main():
    entrada()
    print()
    print()
    print(" A quantidade de acertos  = ", correcao())

main()
